name: 1.0$(rev:.r) # build numbering format

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

variables:
  LibraryName: 'ng-error-handling'
  ExecuteIntegrationTests: false 

jobs:
- template: AzureDevOps/Templates/JobTemplates/Angular/Build_Library_And_Publish_To_NPM.yaml@ALMStuff
  parameters:
    LibraryName: $(LibraryName)
    ExecuteIntegrationTests: $(ExecuteIntegrationTests) 