name: 2.1$(rev:.r) # build numbering format

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff/AzureDevOps/JobTemplates/Angular
    ref: refs/heads/master
    endpoint: GitHub-DrMueller
queue:
  name: Hosted VS2017
  demands: npm

jobs:

- template: templates/npm-with-params.yml  # Template reference
  parameters:
    name: Linux
    vmImage: 'ubuntu-16.04'