resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

variables:
  libraryName: 'ng-data-access'
  executeIntegrationTests: false 

jobs:
- job: CI
  steps:
  - template: AzureDevOps/Templates/StepTemplates/Angular/Initialize_And_Test.yaml@ALMStuff
    parameters:
      executeIntegrationTests: $(executeIntegrationTests)
  - template: AzureDevOps/Templates/StepTemplates/Angular/Build_Production.yaml@ALMStuff
  - template: AzureDevOps/Templates/StepTemplates/Angular/Update_Version.yaml@ALMStuff
    parameters:
      libraryName: $(libraryName)
  - template: AzureDevOps/Templates/StepTemplates/Angular/Publish_NPM.yaml@ALMStuff
    parameters:
      libraryName: $(libraryName)