name: 2.1$(rev:.r) # build numbering format

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff/AzureDevOps/JobTemplates/Angular
    ref: refs/heads/master
    endpoint: GitHub-DrMueller
queue:
  name: Hosted VS2017
  demands: npm

jobs:

- job: Job_1
  displayName: hello
  condition: succeeded()
  pool:
    name: Default
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'