resources:
- repo: self

jobs:

- job: Job_1
  displayName: hello
  condition: succeeded()
  pool:
    name: Default
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'


- job: Job_2
  displayName: test123
  condition: succeeded()
  pool:
    name: Default
