name: 2.2$(rev:.r) # build numbering format

queue:
  name: Hosted VS2017
  demands: npm

resources:
  repositories:
  - repository: ALMStuff
    type: github
    name: DrMueller/ALMStuff
    ref: refs/heads/master
    endpoint: GitHub-DrMueller

variables:
  LibraryName: 'ng-data-access'
  ExecuteIntegrationTests: false 

jobs:
- template: AzureDevOps/Templates/JobTemplates/Angular/Build_And_Publish_To_NPM.yaml@ALMStuff
  parameters:
    LibraryName: $(LibraryName)
    ExecuteIntegrationTests: $(ExecuteIntegrationTests) 